server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/caterapi?useSSL=false
    username: kentoes
    password: enter
    driver-class-name: com.mysql.cj.jdbc.Driver
    #DEVELOP
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE
# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs
# custom config
foto:
  path: foto_cater
images:
  path: /tmp/kentoes-img-compress